export const projectModel = [
  {
    project_name: 'Wallpaper World',
    title: "World's most famous wallpaper",
    desc: 'List of public projects that I have done, and soon I am going to add open-source repo here.',
    image: 'https://bit.ly/dan-abramov',
    tech: ['flutter', 'dart', 'node js', 'kotlin'],
  },
  {
    project_name: 'Webview App',
    title: "World's most famous webview app",
    desc: 'List of public projects that I have done, and soon I am going to add open-source repo here.',
    image: 'https://bit.ly/dan-abramov',
    tech: ['flutter', 'dart'],
  },
  {
    project_name: 'Studit',
    title: "World's most famous education application",
    desc: 'List of public projects that I have done, and soon I am going to add open-source repo here.',
    image: 'https://bit.ly/dan-abramov',
    tech: ['flutter', 'dart'],
  },
  {
    project_name: 'Invoice Generator',
    title: "World's most famous invoice generator app",
    desc: 'List of public projects that I have done, and soon I am going to add open-source repo here.',
    image: 'https://bit.ly/dan-abramov',
    tech: ['flutter', 'dart'],
  },
  {
    project_name: 'News In',
    title: "World's most famous news application",
    desc: 'List of public projects that I have done, and soon I am going to add open-source repo here.',
    image: 'https://bit.ly/dan-abramov',
    tech: ['flutter', 'dart'],
  },
  {
    project_name: 'The Sole Era',
    title: "World's most famous sneakers website",
    desc: 'List of public projects that I have done, and soon I am going to add open-source repo here.',
    image: 'https://bit.ly/dan-abramov',
    tech: ['frontity', 'react', 'javascript', 'wordpress'],
  },
  {
    project_name: 'Garden Blog ',
    title: "World's most famous gardening website",
    desc: 'List of public projects that I have done, and soon I am going to add open-source repo here.',
    image: 'https://bit.ly/dan-abramov',
    tech: ['frontity', 'react', 'javascript', 'wordpress'],
  },
  {
    project_name: 'Transport System',
    title: "World's most famous wallpaper",
    desc: 'List of public projects that I have done, and soon I am going to add open-source repo here.',
    image: 'https://bit.ly/dan-abramov',
    tech: ['next js', 'react', 'laravel', 'javascript'],
  },
];
